# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Don't Panic
tagline:          ''
description:      It's a marathon, not a sprint. So keep calm and carry on.
url:              http://voulipo.me
baseurl:          /

author:
  name:           'voulipo'
  url:            http://voulipo.me/

paginate:         15

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/voulipo/voulipo.github.io
