name: Voulipo's blog
description: Blogging about stuffs
meta_description: "Voulipo's Site, Blogging about stuffs"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://voulipo.me'

# Details for the RSS feed generator
url:            'blog url'
author:         'Voulipo Liu'
